#!/usr/bin/env node

/**
 * Roo-Mini Setup Wizard — interactive credential configuration.
 *
 * Run: npm run setup
 *
 * Prompts for all service API keys and writes them to .env.
 */

import * as readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.join(__dirname, "../../.env");

// ─── Service definitions ───

const SERVICES = [
  {
    title: "🤖 AI Provider",
    vars: [
      { key: "API_KEY", label: "API Key", placeholder: "sk-...", required: true },
      { key: "API_BASE_URL", label: "API Base URL", placeholder: "https://api.deepseek.com/v1", default: "https://api.deepseek.com/v1" },
      { key: "MODEL_NAME", label: "Model Name", placeholder: "deepseek-chat", default: "deepseek-chat" },
    ],
  },
  {
    title: "🐙 GitHub",
    vars: [
      { key: "GITHUB_TOKEN", label: "Personal Access Token", placeholder: "ghp_..." },
    ],
  },
  {
    title: "🔍 Google Search",
    vars: [
      { key: "GOOGLE_API_KEY", label: "API Key", placeholder: "AIza..." },
      { key: "GOOGLE_CSE_ID", label: "Custom Search Engine ID", placeholder: "..." },
    ],
  },
  {
    title: "🔐 Google Workspace (Gmail, Calendar, Drive)",
    vars: [
      { key: "GOOGLE_CLIENT_ID", label: "OAuth Client ID", placeholder: "..." },
      { key: "GOOGLE_CLIENT_SECRET", label: "OAuth Client Secret", placeholder: "..." },
    ],
  },
  {
    title: "📋 Jira",
    vars: [
      { key: "JIRA_HOST", label: "Host", placeholder: "mycompany.atlassian.net" },
      { key: "JIRA_EMAIL", label: "Email", placeholder: "user@company.com" },
      { key: "JIRA_API_TOKEN", label: "API Token", placeholder: "..." },
    ],
  },
  {
    title: "💬 Slack",
    vars: [
      { key: "SLACK_TOKEN", label: "Bot Token", placeholder: "xoxb-..." },
    ],
  },
  {
    title: "🐘 PostgreSQL",
    vars: [
      { key: "PG_URL", label: "Connection URL", placeholder: "postgresql://user:pass@host:5432/db" },
    ],
  },
];

// ─── Helpers ───

function readCurrentEnv() {
  try {
    const content = fs.readFile(ENV_PATH, "utf-8");
    const env = {};
    for (const line of content.split("\n")) {
      const match = line.match(/^([^#=]+)=(.+)$/);
      if (match) {env[match[1].trim()] = match[2].trim();}
    }
    return env;
  } catch { return {}; }
}

async function writeEnv(vars) {
  let content = `# ═══════════════════════════════════════════
# ROO-MINI Configuration
# Generated by npm run setup (${new Date().toISOString().slice(0, 10)})
# ═══════════════════════════════════════════\n\n`;
  for (const [key, value] of Object.entries(vars)) {
    if (value) {content += `${key}=${value}\n`;}
  }
  await fs.writeFile(ENV_PATH, content, "utf-8");
}

// ─── Main ───

async function main() {
  const rl = readline.createInterface({ input, output });
  const current = readCurrentEnv();

  console.log("\n" + "═".repeat(50));
  console.log("  🔧  ROO-MINI SETUP");
  console.log("═".repeat(50));
  console.log("  Configure your API keys and tokens.");
  console.log("  Press Enter to skip any service.\n");

  const vars = { ...current };

  for (const service of SERVICES) {
    console.log(`\n  ${service.title}`);
    console.log("  " + "─".repeat(40));

    for (const v of service.vars) {
      const currentVal = vars[v.key] || "";
      const prompt = `  ${v.label} [${currentVal || v.default || v.placeholder}]: `;
      const input = await rl.question(prompt);
      if (input.trim()) {
        vars[v.key] = input.trim();
      } else if (!vars[v.key] && v.default) {
        vars[v.key] = v.default;
      }
    }
  }

  await writeEnv(vars);
  console.log("\n" + "═".repeat(50));
  console.log("  ✅  Setup complete! Credentials saved to .env");
  console.log("═".repeat(50) + "\n");

  rl.close();
}

main().catch(err => {
  console.error(`❌ Setup failed: ${err.message}`);
  process.exit(1);
});
